# emits ParaphraseDetector.kt — RUN: cd Mindforge ; python tools/emit_paraphrase_detector.py
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "app/src/main/java/com/mindforge/app/ml/ParaphraseDetector.kt"

P = []

def L(s: str) -> None:
    P.append(s)


L("package com.mindforge.app.ml")
L("")
L("import ai.onnxruntime.OnnxTensor")
L("import ai.onnxruntime.OrtEnvironment")
L("import ai.onnxruntime.OrtSession")
L("import android.content.Context")
L("import android.util.Log")
L("import java.nio.LongBuffer")
L("import java.util.Locale")
L("import kotlin.math.exp")
L("import kotlin.math.max")
L("import kotlin.math.min")
L("import kotlin.math.sqrt")
L("import kotlinx.coroutines.Dispatchers")
L("import kotlinx.coroutines.withContext")
L("")
L("/** ONNX BERT + WordPiece vocab (assets/vocab.txt). CLS-cosine if hidden tensors exist else pair-softmax logits. */")
L("class ParaphraseDetector(private val context: Context) {")
L("    private var tokenizer: BertWordpieceTokenizer? = null")
L("    private var session: OrtSession? = null")
L("    private var ortEnvironment: OrtEnvironment? = null")
L("    private var sessionLoaded = false")
L("    private enum class Inference { LEX_ONLY, SOFTMAX_PAIR, CLS_EMBED }")
L("    private var inferenceKind = Inference.LEX_ONLY")
L("")
L("    companion object {")
L("        private const val TAG = \"ParaphraseDetector\"")
L("        private const val MODEL = \"bert_pruned_quantized.onnx\"")
L("        private const val SEQ_LEN = 128")
L("        private const val CLIP = 512")
L("        private const val DUP_TRIM = 0.75f")
L("        private const val LEXICAL_WEIGHT = 0.32f")
L("        private const val CLS_DIM_MIN = 64")
L("    }")
L("")
L("    fun isOnnxModelLoaded(): Boolean = sessionLoaded")
L("")
L("    suspend fun initialize() = withContext(Dispatchers.IO) {")
L("        tokenizer = BertWordpieceTokenizer(context)")
L("        val tz = tokenizer")
L("        if (tz == null || !tz.isVocabLoaded) {")
L("            Log.e(TAG, \"vocab.txt missing — lexical only\")")
L("            closeSessionOnly()")
L("            inferenceKind = Inference.LEX_ONLY")
L("            sessionLoaded = false")
L("            return@withContext")
L("        }")
L("        try {")
L("            ortEnvironment = OrtEnvironment.getEnvironment()")
L("            val blob = context.assets.open(MODEL).readBytes()")
L("            Log.d(TAG, \"ONNX MiB=\" + (blob.size / (1024 * 1024)).toString())")
L("            val opts = OrtSession.SessionOptions().apply {")
L("                setOptimizationLevel(OrtSession.SessionOptions.OptLevel.ALL_OPT)")
L("            }")
L("            session = ortEnvironment!!.createSession(blob, opts)")
L("            sessionLoaded = true")
L("            val probeTok = tz.encodePair(\"hello alpha sentence\", \"hello beta sentence\", SEQ_LEN)")
L("            inferenceKind = session!!.runSessionOnnx(ortEnvironment!!, probeTok).use { probeOutputs(it) }")
L("            Log.i(TAG, \"mode=\" + inferenceKind.name)")
L("        } catch (_: OutOfMemoryError) {")
L("            Log.e(TAG, \"OOM ONNX\")")
L("            closeSessionOnly(); sessionLoaded = false; inferenceKind = Inference.LEX_ONLY")
L("        } catch (e: Exception) {")
L("            Log.e(TAG, \"onnx\", e)")
L("            closeSessionOnly(); sessionLoaded = false; inferenceKind = Inference.LEX_ONLY")
L("        }")
L("    }")
L("")
L("    private fun probeOutputs(results: OrtSession.Result): Inference {")
L("        var hid = false")
L("        var logitTensor = false")
L("        results.forEach { e ->")
L("            if (e.value !is OnnxTensor) return@forEach")
L("            val onnxT = e.value as OnnxTensor")
L("            val rawOnnxValue = onnxT.value")
L("            val nk = e.key?.lowercase(Locale.US) ?: \"\"")
L("            if (nk.contains(\"hidden\")) hid = true")
L("            matrixTokenRows(rawOnnxValue)?.let { rows ->")
L("                if (rows.size in 2..SEQ_LEN + 16 && rows[0].size >= CLS_DIM_MIN) hid = true")
L("            }")
L("            if (flattenParaphraseLogits(rawOnnxValue) != null) logitTensor = true")
L("        }")
L("        return when { hid -> Inference.CLS_EMBED; logitTensor -> Inference.SOFTMAX_PAIR; else -> Inference.SOFTMAX_PAIR }")
L("    }")
L("")
L("    suspend fun calculateSimilarity(tA: String, tB: String): Float = withContext(Dispatchers.Default) {")
L("        val aTrim = tA.trim()")
L("        val bTrim = tB.trim()")
L("        if (aTrim.isEmpty() || bTrim.isEmpty()) return@withContext 0f")
L("        val lex = lexicalMix(aTrim, bTrim)")
L("        val tz = tokenizer")
L("        val sess = session")
L("        val env = ortEnvironment")
L("        if (!sessionLoaded || tz == null || sess == null || env == null || !tz.isVocabLoaded || inferenceKind == Inference.LEX_ONLY)")
L("            return@withContext lex")
L("        val neuralOnnx = kotlin.runCatching {")
L("            when (inferenceKind) {")
L("                Inference.CLS_EMBED -> cosineFromCls(sess, env, tz, aTrim, bTrim)")
L("                Inference.SOFTMAX_PAIR -> paraphraseFromPair(sess, env, tz, aTrim, bTrim)")
L("                Inference.LEX_ONLY -> lex")
L("            }")
L("        }.getOrElse { err -> Log.e(TAG, \"infer\", err); lex }")
L("        max(neuralOnnx, lex * LEXICAL_WEIGHT)")
L("    }")
L("")
L("    suspend fun areDuplicates(x: String, y: String): Boolean = calculateSimilarity(x, y) >= DUP_TRIM")
L("")
L("    private fun OrtSession.runSessionOnnx(environmentBlock: OrtEnvironment, coded: TokenizedInput): OrtSession.Result {")
L("        val ioTensors = mutableListOf<OnnxTensor>()")
L("        fun wrapLongBuffer(rowSlice: LongArray): OnnxTensor {")
L("            val onnxLong = OnnxTensor.createTensor(environmentBlock, LongBuffer.wrap(rowSlice.copyOf(SEQ_LEN)), longArrayOf(1L, SEQ_LEN.toLong()))")
L("            ioTensors += onnxLong")
L("            return onnxLong")
L("        }")
L("        val feedMap = mutableMapOf(\"input_ids\" to wrapLongBuffer(coded.inputIds), \"attention_mask\" to wrapLongBuffer(coded.attentionMask))")
L("        if (\"token_type_ids\" in inputNames) feedMap[\"token_type_ids\"] = wrapLongBuffer(coded.tokenTypeIds)")
L("        return try { run(feedMap) } finally { ioTensors.forEach { kt -> kotlin.runCatching { kt.close() } } }")
L("    }")
L("")
L("    private fun paraphraseFromPair(sess: OrtSession, envBlock: OrtEnvironment, tz: BertWordpieceTokenizer, a: String, b: String): Float {")
L("        val codedPair = tz.encodePair(a.take(CLIP), b.take(CLIP), SEQ_LEN)")
L("        return sess.runSessionOnnx(envBlock, codedPair).use { resObj -> softmaxPickIndex1(resObj) }")
L("    }")
L("")
L("    private fun softmaxPickIndex1(resolved: OrtSession.Result): Float {")
L("        val logits1dRow = logitsFirstFromResult(resolved)")
L("        val soft = softmaxVector(logits1dRow)")
L("        val v = when { soft.size >= 2 -> soft[1]; soft.isEmpty() -> 0f; else -> soft.maxOrNull() ?: 0f }")
L("        return v.coerceIn(0f, 1f)")
L("    }")
L("")
L("    private fun logitsFirstFromResult(resolved: OrtSession.Result): FloatArray {")
L("        val keysOrder = sequenceOf(\"logits\", \"output_logits\", \"prediction_scores\")")
L("        keysOrder.forEach { wantKey -> resolved.forEach { ent ->")
L("            if (!ent.key.equals(wantKey, ignoreCase = true)) return@forEach")
L("            flattenParaphraseLogits((ent.value as OnnxTensor).value)?.let { return it }")
L("        } }")
L("        resolved.forEach { ent -> flattenParaphraseLogits((ent.value as? OnnxTensor)?.value)?.let { return it } }")
L("        throw IllegalStateException(\"logits\")")
L("    }")
L("")
L("    private fun cosineFromCls(sess: OrtSession, envBlock: OrtEnvironment, tz: BertWordpieceTokenizer, a: String, b: String): Float {")
L("        val ea = pooledNormCls(sess, envBlock, tz, a)")
L("        val eb = pooledNormCls(sess, envBlock, tz, b)")
L("        if (ea == null || eb == null) return lexicalMix(a, b)")
L("        val span = min(ea.size, eb.size)")
L("        var dot = 0f")
L("        for (i in 0 until span) dot += ea[i] * eb[i]")
L("        val cos = dot.coerceIn(-1f, 1f)")
L("        return ((cos + 1f) * 0.5f).coerceIn(0f, 1f)")
L("    }")
L("")
L("    private fun pooledNormCls(sess: OrtSession, envBlock: OrtEnvironment, tz: BertWordpieceTokenizer, textBody: String): FloatArray? {")
L("        val singleTok = tz.encodeSingle(textBody.take(CLIP), SEQ_LEN)")
L("        var outVec: FloatArray? = null")
L("        sess.runSessionOnnx(envBlock, singleTok).use { r -> matrixTokenRows(pickHiddenValue(r))?.getOrNull(0)?.clone()?.let { row -> l2NormalizeVector(row); outVec = row } }")
L("        return outVec")
L("    }")
L("")
L("    private fun pickHiddenValue(r: OrtSession.Result): Any? {")
L("        val namesPrefer = sequenceOf(\"last_hidden_state\", \"hidden_states\")")
L("        namesPrefer.forEach { nk -> r.forEach { ent ->")
L("            if (ent.key.equals(nk, ignoreCase = true)) return (ent.value as OnnxTensor).value")
L("        } }")
L("        r.forEach { ent ->")
L("            val ot = ent.value as? OnnxTensor ?: return@forEach")
L("            if (matrixTokenRows(ot.value) != null) return ot.value")
L("        }")
L("        return null")
L("    }")
L("")
L("    @Suppress(\"UNCHECKED_CAST\")")
L("    private fun matrixTokenRows(rawOnnx: Any?): Array<FloatArray>? = try {")
L("        val batch = rawOnnx as Array<*>")
L("        val seq = batch[0] as Array<FloatArray>")
L("        Array(seq.size) { i -> seq[i].clone() }")
L("    } catch (_: Throwable) { null }")
L("")
L("    private fun flattenParaphraseLogits(v: Any?): FloatArray? = when (v) {")
L("        is FloatArray -> if (v.size in 2..12) v.clone() else null")
L("        is Array<*> -> { val z = v.getOrNull(0) as? FloatArray ?: return null; if (z.size in 2..12) z.clone() else null }")
L("        else -> null")
L("    }")
L("")
L("    private fun softmaxVector(v: FloatArray): FloatArray {")
L("        val mx = v.maxOrNull() ?: 0f")
L("        val ex = FloatArray(v.size) { i -> exp((v[i] - mx).toDouble()).toFloat() }")
L("        val s = ex.sum().coerceAtLeast(1e-9f)")
L("        for (i in ex.indices) ex[i] /= s")
L("        return ex")
L("    }")
L("")
L("    private fun l2NormalizeVector(vec: FloatArray) {")
L("        var s = 0.0; for (x in vec) s += x * x.toDouble()")
L("        val inv = sqrt(s).toFloat().coerceAtLeast(1e-9f)")
L("        for (i in vec.indices) vec[i] /= inv")
L("    }")
L("")
L("    private fun lexicalMix(sa: String, sb: String): Float {")
L("        val w1 = sa.lowercase(Locale.US).split(Regex(\"\\\\W+\")).filter { it.length > 1 }.toSet()")
L("        val w2 = sb.lowercase(Locale.US).split(Regex(\"\\\\W+\")).filter { it.length > 1 }.toSet()")
L("        val jac = when {")
L("            w1.isEmpty() || w2.isEmpty() -> 0f")
L("            else -> { val ix = w1.intersect(w2).size; val uni = w1.union(w2).size; if (uni > 0) ix.toFloat() / uni else 0f }")
L("        }")
L("        val tri = trigramDiceScore(sa, sb)")
L("        val minW = min(w1.size.coerceAtLeast(triApprox(sa)), w2.size.coerceAtLeast(triApprox(sb)))")
L("        val pen = when { minW <= 2 -> 0.55f; minW <= 4 -> 0.72f; minW <= 6 -> 0.88f; else -> 1f }")
L("        val lr = min(sa.length, sb.length).toFloat() / max(sa.length, sb.length).toFloat()")
L("        val blend = max(jac * 0.85f + lr * 0.15f, tri * 0.92f + lr * 0.08f)")
L("        return (blend * pen).coerceIn(0f, 1f)")
L("    }")
L("")
L("    private fun triApprox(txt: String): Int = alphanumericStrip(txt).length.coerceAtLeast(3) / 4")
L("")
L("    private fun alphanumericStrip(s: String) = buildString(s.length) { for (ch in s.lowercase(Locale.US)) if (ch.isLetterOrDigit()) append(ch) }")
L("")
L("    private fun trigramDiceScore(sa: String, sb: String): Float {")
L("        fun grams(t: String): Set<String> {")
L("            val c = alphanumericStrip(t)")
L("            if (c.length < 3) return emptySet()")
L("            val g = HashSet<String>(c.length - 2)")
L("            for (i in 0..c.length - 3) g.add(c.substring(i, i + 3))")
L("            return g")
L("        }")
L("        val A = grams(sa); val B = grams(sb)")
L("        if (A.isEmpty() || B.isEmpty()) return 0f")
L("        var inter = 0; val Sm = if (A.size <= B.size) A else B; val La = if (A.size <= B.size) B else A")
L("        for (g in Sm) if (La.contains(g)) inter++")
L("        return 2f * inter / (A.size + B.size)")
L("    }")
L("")
L("    private fun closeSessionOnly() { kotlin.runCatching { session?.close() }; session = null; sessionLoaded = false }")
L("")
L("    fun cleanup() { closeSessionOnly(); kotlin.runCatching { ortEnvironment?.close() }; ortEnvironment = null; tokenizer = null; inferenceKind = Inference.LEX_ONLY }")
L("")
L("}")
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(P), encoding="utf-8")
print("Wrote", OUT, "lines", len(P))
